version: "3.7"
services:
        apache:
                container_name: apache
                build: ./docker/apache
                ports:
                        - ${APACHE_PORT}:80
                depends_on:
                        - php
                volumes:
                        - ./docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
                        - .:${PROJECT_DIR}
                        - ./docker/apache/log:/var/log/apache2

        mysql:
                container_name: mysql
                image: mysql
                ports:
                        - ${MYSQL_PORT}:3306
                restart: always
                volumes:
                        - ./docker/data/db:/var/lib/mysql
                command: --default-authentication-plugin=mysql_native_password
                environment:
                        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                        MYSQL_DATABASE: ${MYSQL_DATABASE}
                        MYSQL_USER: ${MYSQL_USER}
                        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        
        php:
                container_name: php
                build: ./docker/php
                ports:
                        - ${PHP_PORT}:9000
                links:
                        - mysql
                working_dir: ${PROJECT_DIR}
                volumes:
                        - .:${PROJECT_DIR}
               
